# pre-commit plugin configuration
# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/jedie/cli-base-utilities
    rev: v0.27.3
    hooks:
      - id: update-readme-history
